name: Deploy Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start docker containers
      run: |
        docker compose up --wait --wait-timeout 120 --detach -e DIR="."
        sleep 10
        docker container ls
        docker ps -a

    - name: Show containers
      run: docker container ls
